name: Nightly CI
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
    inputs: {}
jobs:
  unit:
    if: github.repository == 'yussufsh/quay'
    name: Run all Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: ['ppc64le']
    steps:

    - name: Install dependencies and run all tests on ppc64le
      if: matrix.platform  == 'ppc64le'
      uses: appleboy/ssh-action@v0.1.10
      env:
        GH_REPOSITORY: ${{ github.server_url }}/${{ github.repository }}
        GH_REF: ${{ github.ref }}
      with:
        host: ${{ secrets.BUILDER_PPC64LE_SSH_HOST }}
        username: ${{ secrets.BUILDER_PPC64LE_SSH_USER }}
        key: ${{ secrets.BUILDER_PPC64LE_SSH_KEY }}
        envs: GH_REPOSITORY,GH_REF
        command_timeout: 200m
        script: |
          apt-get update -y
          apt-get -y install build-essential libgpgme-dev libldap2-dev libsasl2-dev swig python3.9-dev python3-pip findutils git
          apt-get -y install libffi-dev libssl-dev libjpeg-dev libpq-dev
          git clone ${GH_REPOSITORY} build
          cd build  && git checkout ${GH_REF}
          GRPC_LATEST=$(grep "grpcio" requirements.txt |cut -d "=" -f 3)
          export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 && python3 -m pip install -qq grpcio==${GRPC_LATEST}
          cat requirements-dev.txt | grep tox | xargs python3 -m pip -qq install

          #Unit
          tox -e py39-unit

          #e2e
          tox -e py39-e2e

          #registry
          tox -e py39-registry

